# Generated by Django 4.0 on 2023-06-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='medicion',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
