# Generated by Django 4.0 on 2023-06-19 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prueba_tecnica", "0002_alter_medicion_medicion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicion",
            old_name="estado",
            new_name="machine_status",
        ),
        migrations.RenameField(
            model_name="medicion",
            old_name="medicion",
            new_name="valor_medicion",
        ),
    ]
